name: stated_result
description: A bloc that accepts async source as input
version: 0.2.0-preview.5
homepage: https://github.com/timnew/stated_result

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  mockito: ^4.1.3

flutter:
